### ISSUE TITLE
Real time saving

### ISSUE THREAD

**Issue by Godsfunambulator** [oviradoi/npp-explorer-plugin#26]
It seems that this plugin only saves the favorites to the .dat file once you exit Notepad++, which seems to be the reason I have lost favorites.  So if Notepad++ crashes (as seems more common when using this plugin) you will lose any favorites you have saved since your last non-crash exit.  If you haven't already done it, please see if you can save favorites as you create them.

It would also be nice if we could restructure the favorites by moving file shortcuts from one grouping to another, however that is a suggestion for improvement and not a bug.

**Comment by oviradoi** [comment]
This has been fixed in version 1.9.5.0

**Comment by Godsfunambulator** [comment]
Thank you!  Why does Notepad++ Explorer Admin Plug-in menu still show latest version is 1.9.4 with no updates available?  Will you be pushing out the update via Notepad++ plug-in Admin update or must we install from github directly?

**Comment by oviradoi** [comment]
I have already pushed the new version to Plugin Admin's repository, however the Notepad++ team did not release it yet. Once they release a new version of the plugins repository, it will show up in Plugins Admin.

**Comment by Godsfunambulator** [comment]
@oviradoi,
Just want to say thank you for updating this.  I waited for the update to get pushed out.  Before I updated this add-on adding a favorite group crashed Notepad++ and I lost the couple of groupings that I just created.  I restarted and updated this add-on, and although Notepad++ still crashed (different group name), I didn't lose the favorites that time.  Thank you very much!  I really like this add-on!

As a side note, adding new "groups" to the favorite tree seems to crash Notepad++ fairly frequently.  Not sure why, but not a huge deal since you made the folders save in real-time.
